version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - конфигами
  - asyncio
  - Docstrings
  - fastapi
  - loguru
  - pydantic
  - Pydantic
  - pytest
  - pywin
  - uvicorn
  - venv
ignoreWords: []
import: []
